// Original bilingual campaign content. Combat numbers are base values; depth scaling belongs to the engine.
const L = (en, pl) => ({ en, pl });
const skill = (id, en, pl, descEn, descPl, kind, cost, cooldown, damage, color) => ({
  id,
  name: L(en, pl),
  desc: L(descEn, descPl),
  kind,
  cost,
  cooldown,
  damage,
  color,
});

export const CLASSES = [
  {
    id: 'warden',
    name: L('Oath Warden', 'Strażnik Przysięgi'),
    desc: L(
      'A steadfast guardian with a sun-forged blade. Hold the line, scatter crowds, and outlast the darkness.',
      'Niezłomny obrońca ze słonecznym ostrzem. Utrzymuj pozycję, rozbijaj grupy i przetrwaj napór ciemności.',
    ),
    color: 0xeebc64,
    hp: 150,
    mana: 80,
    damage: 19,
    speed: 4.5,
    range: 2.2,
    weapon: 'sword',
    passive: L(
      'Iron resolve · the greatest starting vitality.',
      'Żelazna wola · najwyższa początkowa żywotność.',
    ),
    origin: L(
      'You abandoned the Order when it demanded silence. Your oath was to the living, never to a throne.',
      'Opuściłeś Zakon, kiedy zażądał milczenia. Twoja przysięga chroniła żywych, nigdy tron.',
    ),
    skills: [
      skill(
        'sun_sweep',
        'Sun Sweep',
        'Słoneczne Cięcie',
        'Sweep your blade through nearby enemies.',
        'Zatocz ostrzem łuk, uderzając pobliskich wrogów.',
        'cleave',
        14,
        4,
        43,
        0xffd36b,
      ),
      skill(
        'oath_charge',
        'Oath Charge',
        'Szarża Przysięgi',
        'Burst forward through danger and strike a path.',
        'Rusz naprzód przez niebezpieczeństwo, torując sobie drogę.',
        'dash',
        18,
        7,
        38,
        0xffe3a3,
      ),
      skill(
        'dawn_prayer',
        'Dawn Prayer',
        'Modlitwa Świtu',
        'Recover health in a burst of golden light.',
        'Odzyskaj zdrowie w rozbłysku złotego światła.',
        'heal',
        30,
        14,
        65,
        0xffedba,
      ),
    ],
  },
  {
    id: 'ranger',
    name: L('Veil Ranger', 'Łowczyni Zasłony'),
    desc: L(
      'A swift pathfinder whose runic bow commands distance. Keep moving and punish enemies before they can close in.',
      'Zwinna tropicielka z runicznym łukiem. Pozostawaj w ruchu i raź przeciwników, zanim zdołają się zbliżyć.',
    ),
    color: 0x7de1a1,
    hp: 105,
    mana: 95,
    damage: 16,
    speed: 5.7,
    range: 9,
    weapon: 'bow',
    passive: L(
      'Trailwalker · the fastest movement speed.',
      'Wędrowczyni · najwyższa prędkość ruchu.',
    ),
    origin: L(
      'Your forest learned to whisper in the voices of missing children. You followed the whispers below.',
      'Twój las zaczął szeptać głosami zaginionych dzieci. Podążyłaś za szeptem w podziemia.',
    ),
    skills: [
      skill(
        'star_arrow',
        'Star Arrows',
        'Gwiezdne Strzały',
        'Release three runic arrows in a spreading volley.',
        'Wystrzel trzy runiczne strzały w rozchodzącej się salwie.',
        'projectile',
        12,
        3,
        48,
        0x8ef7c0,
      ),
      skill(
        'wind_step',
        'Wind Step',
        'Krok Wiatru',
        'Dash out of a closing trap or through the enemy line.',
        'Wyskocz z pułapki lub przemknij przez szeregi wroga.',
        'dash',
        16,
        6,
        29,
        0xc5ffe5,
      ),
      skill(
        'thorn_sigil',
        'Thorn Sigil',
        'Pieczęć Cierni',
        'Place a living sigil that attacks enemies nearby.',
        'Postaw żywą pieczęć atakującą pobliskich wrogów.',
        'totem',
        28,
        13,
        24,
        0x49d888,
      ),
    ],
  },
  {
    id: 'arcanist',
    name: L('Rune Arcanist', 'Runiczna Arkanistka'),
    desc: L(
      'A scholar of impossible geometry. Devastating spells and a deep mana reserve reward precise positioning.',
      'Badaczka niemożliwej geometrii. Niszczące zaklęcia i duża rezerwa many nagradzają dobre ustawienie.',
    ),
    color: 0xb797ff,
    hp: 90,
    mana: 145,
    damage: 20,
    speed: 4.8,
    range: 8.5,
    weapon: 'staff',
    passive: L(
      'Deep well · the largest starting mana reserve.',
      'Głębokie źródło · największy początkowy zapas many.',
    ),
    origin: L(
      'Your mentor erased a name from every history book. The same name now appears in your dreams: Aster.',
      'Twoja mentorka wymazała jedno imię ze wszystkich kronik. Teraz wraca ono w twoich snach: Aster.',
    ),
    skills: [
      skill(
        'astral_lance',
        'Astral Lances',
        'Astralne Lance',
        'Hurl three lances of astral energy in a fan.',
        'Ciśnij trzema lancami energii astralnej rozłożonymi w wachlarz.',
        'projectile',
        16,
        3,
        62,
        0xb69aff,
      ),
      skill(
        'rift_nova',
        'Rift Nova',
        'Rozbłysk Szczeliny',
        'Unleash a circular wave of runic force.',
        'Wyzwól kolistą falę runicznej mocy.',
        'nova',
        30,
        8,
        67,
        0xd6b9ff,
      ),
      skill(
        'echo_pillar',
        'Echo Pillar',
        'Filar Echa',
        'Summon a stationary conduit that repeatedly strikes foes.',
        'Przywołaj nieruchomy przekaźnik wielokrotnie rażący wrogów.',
        'totem',
        32,
        14,
        29,
        0x9266ef,
      ),
    ],
  },
  {
    id: 'reaver',
    name: L('Ash Reaver', 'Popielny Rozpruwacz'),
    desc: L(
      'An exiled arena champion wielding a heavy axe. Close the gap and unleash the strongest weapon strikes.',
      'Wygnany mistrz areny z ciężkim toporem. Skracaj dystans i zadawaj najpotężniejsze ciosy bronią.',
    ),
    color: 0xf78865,
    hp: 130,
    mana: 75,
    damage: 26,
    speed: 5,
    range: 2.5,
    weapon: 'axe',
    passive: L(
      'Ember renewal · each defeated enemy restores 2 + 0.15 × depth health. The strongest base weapon damage.',
      'Odnowa żaru · każdy pokonany wróg przywraca 2 + 0,15 × głębina zdrowia. Najwyższe podstawowe obrażenia broni.',
    ),
    origin: L(
      'The city called you a monster for refusing an execution. Now its true monsters wear your old chains.',
      'Miasto nazwało cię potworem, gdy odmówiłeś wykonania wyroku. Teraz prawdziwe potwory noszą twoje dawne kajdany.',
    ),
    skills: [
      skill(
        'cinder_arc',
        'Cinder Arc',
        'Łuk Żaru',
        'Bring your axe down in a devastating wide strike.',
        'Opuść topór w niszczycielskim, szerokim zamachu.',
        'cleave',
        14,
        4,
        62,
        0xff956d,
      ),
      skill(
        'ember_rush',
        'Ember Rush',
        'Pęd Iskier',
        'Charge through enemies in a trail of embers.',
        'Przemknij przez wrogów, pozostawiając smugę iskier.',
        'dash',
        18,
        6,
        46,
        0xff734d,
      ),
      skill(
        'furnace_roar',
        'Furnace Roar',
        'Ryk Pieca',
        'Release stored fury as a blazing shockwave.',
        'Uwolnij nagromadzony gniew jako płomienną falę uderzeniową.',
        'nova',
        28,
        10,
        75,
        0xffbe6d,
      ),
    ],
  },
  {
    id: 'oracle',
    name: L('Tide Oracle', 'Wyrocznia Przypływu'),
    desc: L(
      'A dream-reader who channels the drowned stars. Balance ranged magic, healing, and protective spirit totems.',
      'Czytająca sny przewodniczka zatopionych gwiazd. Łącz magię dystansową, leczenie i duchowe totemy.',
    ),
    color: 0x76dce8,
    hp: 115,
    mana: 120,
    damage: 17,
    speed: 4.8,
    range: 7.5,
    weapon: 'orb',
    passive: L(
      'Even tide · balanced vitality and abundant mana.',
      'Spokojny przypływ · równowaga żywotności i dużego zapasu many.',
    ),
    origin: L(
      'You remember a city that never existed. Beneath its waves, someone remembers you.',
      'Pamiętasz miasto, które nigdy nie istniało. Pod jego falami ktoś pamięta ciebie.',
    ),
    skills: [
      skill(
        'moon_shard',
        'Moon Shards',
        'Odłamki Księżyca',
        'Cast three spreading shards of condensed moonlight.',
        'Ciśnij trzema rozchodzącymi się odłamkami księżycowego światła.',
        'projectile',
        12,
        3,
        45,
        0x8deaf7,
      ),
      skill(
        'returning_tide',
        'Returning Tide',
        'Powracająca Fala',
        'Restore health with the memory of an unbroken body.',
        'Przywróć zdrowie wspomnieniem ciała wolnego od ran.',
        'heal',
        24,
        11,
        72,
        0xb6fff1,
      ),
      skill(
        'ancestor_lantern',
        'Ancestor Lantern',
        'Latarnia Przodków',
        'Call a spirit lantern to strike nearby enemies.',
        'Przywołaj duchową latarnię rażącą pobliskich przeciwników.',
        'totem',
        26,
        12,
        26,
        0x59cedc,
      ),
    ],
  },
];

const enemy = (
  id,
  en,
  pl,
  hp,
  damage,
  speed,
  range,
  color,
  shape,
  behavior,
  xp,
  scale,
  loreEn,
  lorePl,
) => ({
  id,
  name: L(en, pl),
  hp,
  damage,
  speed,
  range,
  color,
  shape,
  behavior,
  xp,
  scale,
  lore: L(loreEn, lorePl),
});
export const ENEMIES = Object.fromEntries(
  [
    enemy(
      'hollow_guard',
      'Hollow Guard',
      'Pusty Strażnik',
      35,
      7,
      2.5,
      1.6,
      0x8393a3,
      'humanoid',
      'melee',
      13,
      1,
      'An empty suit still obeying its last command.',
      'Pusta zbroja wciąż wykonująca ostatni rozkaz.',
    ),
    enemy(
      'crypt_crawler',
      'Crypt Crawler',
      'Pełzacz Krypt',
      24,
      6,
      3.5,
      1.3,
      0xa584b4,
      'spider',
      'melee',
      10,
      0.8,
      'It nests in cracks where old prayers gather.',
      'Gnieździ się w szczelinach, gdzie zbierają się dawne modlitwy.',
    ),
    enemy(
      'candle_wisp',
      'Candle Wisp',
      'Ognik Świec',
      25,
      8,
      2.1,
      6.5,
      0x68c5d5,
      'wisp',
      'ranged',
      15,
      0.8,
      'A watchman’s lantern, searching without its keeper.',
      'Latarnia wartownika, szukająca bez swego opiekuna.',
    ),
    enemy(
      'bell_hound',
      'Bell Hound',
      'Dzwonowy Ogar',
      42,
      10,
      3.7,
      1.6,
      0x927c68,
      'hound',
      'charger',
      18,
      1,
      'It hears the city’s fear as a hunting horn.',
      'Strach miasta słyszy niczym myśliwski róg.',
    ),
    enemy(
      'thorn_lurker',
      'Thorn Lurker',
      'Cierniowy Czyhacz',
      48,
      10,
      2.7,
      6,
      0x70a27f,
      'humanoid',
      'ranged',
      20,
      1.1,
      'Roots bind a forgotten archer to a twisted wooden bow; each arrow carries the grove’s last promise.',
      'Korzenie wiążą zapomnianego łucznika z wygiętym drewnianym łukiem; każda strzała niesie ostatnią obietnicę gaju.',
    ),
    enemy(
      'spore_weaver',
      'Spore Weaver',
      'Tkacz Zarodników',
      33,
      9,
      3.2,
      6,
      0xc298ca,
      'spider',
      'ranged',
      20,
      0.9,
      'Its luminous silk carries dreams between trees.',
      'Jego świecąca nić przenosi sny między drzewami.',
    ),
    enemy(
      'bark_colossus',
      'Bark Colossus',
      'Kolos Kory',
      95,
      15,
      1.6,
      2,
      0x8c795b,
      'golem',
      'melee',
      30,
      1.45,
      'A grove guardian warped by borrowed sorrow.',
      'Strażnik gaju wypaczony cudzym smutkiem.',
    ),
    enemy(
      'moss_caller',
      'Moss Caller',
      'Zaklinacz Mchu',
      53,
      9,
      2,
      6,
      0x74d7a0,
      'humanoid',
      'summoner',
      28,
      1.1,
      'The voices it calls are echoes, not the dead.',
      'Przyzywane głosy należą do ech, nie do umarłych.',
    ),
    enemy(
      'mirror_knight',
      'Mirror Knight',
      'Lustrzany Rycerz',
      70,
      13,
      2.8,
      1.8,
      0x939ce1,
      'humanoid',
      'melee',
      27,
      1.1,
      'It protects a reflection that has lost its owner.',
      'Chroni odbicie, które utraciło właściciela.',
    ),
    enemy(
      'prism_mote',
      'Prism Mote',
      'Pryzmatyczny Pyłek',
      42,
      12,
      2.7,
      7,
      0xc89fee,
      'wisp',
      'ranged',
      26,
      0.8,
      'A splinter of a future that never happened.',
      'Drzazga przyszłości, która nigdy nie nadeszła.',
    ),
    enemy(
      'shard_skitter',
      'Shard Skitter',
      'Odłamkowy Skoczek',
      46,
      13,
      4.1,
      1.5,
      0x87cbdc,
      'spider',
      'charger',
      27,
      0.9,
      'Each leg walks through a different possibility.',
      'Każda noga stąpa po innej możliwości.',
    ),
    enemy(
      'glass_scribe',
      'Glass Scribe',
      'Szklany Skryba',
      62,
      13,
      2,
      7,
      0xb396cc,
      'humanoid',
      'summoner',
      33,
      1.05,
      'It rewrites intruders as errors in the archive.',
      'Przepisuje intruzów jako błędy archiwum.',
    ),
    enemy(
      'chain_sentinel',
      'Chain Sentinel',
      'Łańcuchowy Wartownik',
      93,
      16,
      2.6,
      2,
      0xb48e75,
      'humanoid',
      'melee',
      34,
      1.15,
      'Its sentence outlived the law that gave it meaning.',
      'Jego wyrok przetrwał prawo, które nadawało mu sens.',
    ),
    enemy(
      'furnace_hound',
      'Furnace Hound',
      'Piecowy Ogar',
      67,
      17,
      4,
      1.7,
      0xef9360,
      'hound',
      'charger',
      33,
      1.1,
      'Forged to seek sparks escaping the great engine.',
      'Wykuty, by tropić iskry uciekające z wielkiej machiny.',
    ),
    enemy(
      'slag_titan',
      'Slag Titan',
      'Żużlowy Tytan',
      140,
      22,
      1.5,
      2.4,
      0xa57966,
      'golem',
      'melee',
      44,
      1.55,
      'A failed vessel for a perfect, obedient soul.',
      'Nieudane naczynie dla idealnej, posłusznej duszy.',
    ),
    enemy(
      'ember_channeler',
      'Ember Channeler',
      'Przewodnik Żaru',
      67,
      17,
      2.2,
      7.5,
      0xf6b067,
      'humanoid',
      'ranged',
      37,
      1.05,
      'Its furnace-forged bow launches ember-tipped arrows, feeding the dark with memories of summer.',
      'Jego łuk wykuty w piecu wystrzeliwuje strzały o żarzących się grotach, karmiąc mrok wspomnieniami lata.',
    ),
    enemy(
      'tidebound',
      'Tidebound',
      'Związany Przypływem',
      106,
      18,
      2.7,
      1.8,
      0x67a9b7,
      'humanoid',
      'melee',
      40,
      1.15,
      'A citizen who cannot remember the shore.',
      'Mieszkaniec, który nie potrafi przypomnieć sobie brzegu.',
    ),
    enemy(
      'abyss_jelly',
      'Abyss Lantern',
      'Latarnia Otchłani',
      63,
      18,
      2.4,
      7.5,
      0x8adfe3,
      'wisp',
      'ranged',
      38,
      1,
      'It shines with the names the ocean swallowed.',
      'Świeci imionami połkniętymi przez ocean.',
    ),
    enemy(
      'coral_maw',
      'Coral Maw',
      'Koralowa Paszcza',
      86,
      21,
      3.6,
      1.8,
      0xce90a9,
      'hound',
      'charger',
      41,
      1.2,
      'A reef that learned to follow the tide inland.',
      'Rafa, która nauczyła się podążać za przypływem na ląd.',
    ),
    enemy(
      'undertow_cantor',
      'Undertow Cantor',
      'Kantor Głębin',
      90,
      17,
      2,
      7,
      0x75a5d5,
      'humanoid',
      'summoner',
      47,
      1.15,
      'The chorus promises a home beneath all homes.',
      'Jego chór obiecuje dom pod wszystkimi domami.',
    ),
    enemy(
      'void_paladin',
      'Void Paladin',
      'Paladyn Pustki',
      140,
      23,
      2.9,
      2,
      0xad91ce,
      'humanoid',
      'melee',
      52,
      1.25,
      'The first oath made flesh: no light shall leave.',
      'Pierwsza przysięga przybrała ciało: żadne światło nie ucieknie.',
    ),
    enemy(
      'star_devourer',
      'Star Devourer',
      'Pożeracz Gwiazd',
      104,
      23,
      4.1,
      1.9,
      0x7366ad,
      'hound',
      'charger',
      49,
      1.3,
      'It is hungry for possibilities, never flesh.',
      'Jest głodny możliwości, nigdy ciała.',
    ),
    enemy(
      'null_weaver',
      'Null Weaver',
      'Tkacz Nicości',
      86,
      22,
      2.6,
      8,
      0xc07ddd,
      'spider',
      'ranged',
      49,
      1.15,
      'It knots the empty spaces between moments.',
      'Wiąże puste przestrzenie pomiędzy chwilami.',
    ),
    enemy(
      'echo_archon',
      'Echo Archon',
      'Archont Echa',
      115,
      21,
      2.1,
      7.5,
      0xc6aef6,
      'wisp',
      'summoner',
      58,
      1.3,
      'A council of discarded selves speaking as one.',
      'Rada odrzuconych istnień przemawiająca jednym głosem.',
    ),
  ].map((entry) => [entry.id, entry]),
);

const bosses = [
  [
    'bell_keeper',
    'Veyr, the Bell Keeper',
    'Veyr, Strażnik Dzwonu',
    420,
    16,
    2.2,
    2.5,
    0xdfad64,
    'golem',
    'melee',
    160,
    2.1,
    'Resonant slam',
    'Rezonujący cios',
    'Move outside the marked circle before the bell strikes.',
    'Opuść oznaczony krąg, zanim uderzy dzwon.',
  ],
  [
    'root_matriarch',
    'The Root Matriarch',
    'Matrona Korzeni',
    620,
    20,
    1.8,
    6,
    0x80c697,
    'spider',
    'summoner',
    240,
    2.2,
    'Thorn bloom',
    'Rozkwit cierni',
    'Clear summoned creatures and keep an escape route open.',
    'Usuwaj przywołane istoty i zachowaj drogę ucieczki.',
  ],
  [
    'glass_oracle',
    'Ilyra, the Glass Oracle',
    'Ilyra, Szklana Wyrocznia',
    780,
    23,
    2.5,
    8,
    0xbda1f4,
    'wisp',
    'ranged',
    320,
    2,
    'Prismatic stars',
    'Pryzmatyczne gwiazdy',
    'Circle the arena and cross the gaps between projectiles.',
    'Okrążaj arenę i korzystaj z przerw między pociskami.',
  ],
  [
    'iron_judge',
    'Kord, the Iron Judge',
    'Kord, Żelazny Sędzia',
    1020,
    29,
    2.1,
    3,
    0xe79c66,
    'golem',
    'charger',
    410,
    2.4,
    'Final sentence',
    'Ostateczny wyrok',
    'Bait the charge, sidestep, and attack during recovery.',
    'Sprowokuj szarżę, uskocz i zaatakuj podczas odpoczynku.',
  ],
  [
    'drowned_king',
    'Orren, the Drowned King',
    'Orren, Zatopiony Król',
    1220,
    30,
    2.2,
    7.5,
    0x79d6df,
    'humanoid',
    'summoner',
    510,
    2.2,
    'Court of tides',
    'Dwór przypływów',
    'Defeat his court before it surrounds you.',
    'Pokonaj jego dworzan, zanim cię otoczą.',
  ],
  [
    'first_keeper',
    'Aster, the First Keeper',
    'Aster, Pierwszy Strażnik',
    1600,
    34,
    2.7,
    8,
    0xd3a4ff,
    'humanoid',
    'ranged',
    800,
    2.4,
    'The unmaking',
    'Rozplatanie',
    'Watch the ground, conserve healing, and strike between waves.',
    'Obserwuj podłoże, oszczędzaj leczenie i atakuj pomiędzy falami.',
  ],
];
for (const [
  id,
  en,
  pl,
  hp,
  damage,
  speed,
  range,
  color,
  shape,
  behavior,
  xp,
  scale,
  moveEn,
  movePl,
  tipEn,
  tipPl,
] of bosses) {
  ENEMIES[id] = {
    id,
    name: L(en, pl),
    hp,
    damage,
    speed,
    range,
    color,
    shape,
    behavior,
    xp,
    scale,
    boss: true,
    signature: L(moveEn, movePl),
    tip: L(tipEn, tipPl),
    lore: L(tipEn, tipPl),
  };
}

export const CHAPTERS = [
  {
    id: 'ashen_bells',
    name: L('The Ashen Belfry', 'Popielna Dzwonnica'),
    subtitle: L(
      'Chapter I · A city that forgot the dawn',
      'Rozdział I · Miasto, które zapomniało świt',
    ),
    story: L(
      'For seven nights, the bells of Lumenfall have rung beneath the streets. Each morning, another name vanishes from the city’s memory. Your sister Mira left a lantern at your door and a note: “If you forget me, follow the sound.” Descend beneath the abandoned belfry. Someone below is still ringing for help.',
      'Od siedmiu nocy pod ulicami Lumenfall biją dzwony. Każdego ranka kolejne imię znika z pamięci miasta. Twoja siostra Mira zostawiła pod drzwiami latarnię i kartkę: „Jeżeli mnie zapomnisz, podążaj za dźwiękiem”. Zejdź pod opuszczoną dzwonnicę. Ktoś na dole wciąż wzywa pomocy.',
    ),
    objective: L(
      'Find Mira’s trail and silence the Bell Keeper.',
      'Odnajdź ślad Miry i ucisz Strażnika Dzwonu.',
    ),
    color: 0x62bfc5,
    floorColor: 0x28383c,
    wallColor: 0x47525a,
    fogColor: 0x101d27,
    enemies: ['hollow_guard', 'crypt_crawler', 'candle_wisp', 'bell_hound'],
    boss: 'bell_keeper',
    floorNames: [
      L('The Forgotten Parish', 'Zapomniana Parafia'),
      L('Under the Last Bell', 'Pod Ostatnim Dzwonem'),
    ],
    lore: [
      {
        title: L('Mira’s note', 'Notatka Miry'),
        text: L(
          'You always said a lantern is only useful when someone carries it. I borrowed yours. Please be angry with me when I return. That will mean you remember.',
          'Zawsze mówisz, że latarnia przydaje się tylko wtedy, gdy ktoś ją niesie. Pożyczyłam twoją. Proszę, gniewaj się na mnie po powrocie. To będzie znaczyło, że pamiętasz.',
        ),
      },
      {
        title: L('The seventh bell', 'Siódmy dzwon'),
        text: L(
          'Six bells called the faithful. The seventh was cast without a tongue. No one knew what it was meant to announce, until it rang by itself.',
          'Sześć dzwonów wzywało wiernych. Siódmy odlano bez serca. Nikt nie wiedział, co miał zwiastować, dopóki nie zadzwonił sam.',
        ),
      },
      {
        title: L('An unfinished roll call', 'Niedokończony apel'),
        text: L(
          'The watch roster lists forty guards. Every name has faded except Veyr. Beside it: “Remain until relieved.” No relief ever came.',
          'Spis warty wymienia czterdziestu strażników. Wszystkie imiona wyblakły poza Veyrem. Obok zapisano: „Zostań do zmiany”. Zmiana nigdy nie nadeszła.',
        ),
      },
    ],
    dialogue: [
      {
        speaker: L('Sella, lantern keeper', 'Sella, opiekunka latarni'),
        text: L(
          'Your sister passed here carrying light that cast no shadow. She asked me to remember her name. I wrote it on my hands.',
          'Twoja siostra przeszła tędy ze światłem, które nie rzucało cienia. Poprosiła, żebym pamiętała jej imię. Zapisałam je na dłoniach.',
        ),
      },
      {
        speaker: L('Veyr’s echo', 'Echo Veyra'),
        text: L(
          'The bell was never a warning. It was a heartbeat. Go deeper. The heart is frightened.',
          'Dzwon nigdy nie był ostrzeżeniem. Był biciem serca. Zejdź głębiej. Serce się boi.',
        ),
      },
    ],
    completion: L(
      'Veyr’s armor falls empty. Beneath it rests a living root wrapped around Mira’s blue ribbon. The bells fall silent; the roots begin to sing.',
      'Zbroja Veyra opada pusta. Pod nią spoczywa żywy korzeń opleciony błękitną wstążką Miry. Dzwony milkną; korzenie zaczynają śpiewać.',
    ),
  },
  {
    id: 'rootbound',
    name: L('The Rootbound Gardens', 'Ogrody Splątanych Korzeni'),
    subtitle: L('Chapter II · Every root remembers', 'Rozdział II · Każdy korzeń pamięta'),
    story: L(
      'An impossible forest grows beneath the city. Its leaves hold memories stolen from the streets above: a first snowfall, a mother’s song, your sister’s laughter. The Matriarch keeps them safe, but her roots are breaking the foundations. A gardener named Edrin offers two uncertain paths: tend the ancient roots, or scatter their seeds into the unknown.',
      'Pod miastem rośnie niemożliwy las. Jego liście przechowują wspomnienia skradzione z ulic: pierwszy śnieg, piosenkę matki, śmiech twojej siostry. Matrona je chroni, lecz jej korzenie rozrywają fundamenty. Ogrodnik Edrin proponuje dwie niepewne drogi: opiekować się starymi korzeniami albo rozsypać ich nasiona w nieznane.',
    ),
    objective: L(
      'Reach the memory tree and confront its guardian.',
      'Dotrzyj do drzewa pamięci i zmierz się z jego strażniczką.',
    ),
    color: 0x87c58a,
    floorColor: 0x263d35,
    wallColor: 0x425446,
    fogColor: 0x10261e,
    enemies: ['thorn_lurker', 'spore_weaver', 'bark_colossus', 'moss_caller'],
    boss: 'root_matriarch',
    floorNames: [
      L('The Whispering Beds', 'Szepczące Grządki'),
      L('The Memory Tree', 'Drzewo Pamięci'),
    ],
    lore: [
      {
        title: L('A gardener’s ledger', 'Księga ogrodnika'),
        text: L(
          'Planting 81: laughter, recovered from a deserted nursery. Planting 82: the smell of bread. Planting 83: a name I cannot bring myself to write.',
          'Nasadzenie 81: śmiech, odzyskany z opuszczonej izby dziecięcej. Nasadzenie 82: zapach chleba. Nasadzenie 83: imię, którego nie potrafię zapisać.',
        ),
      },
      {
        title: L('The green covenant', 'Zielone przymierze'),
        text: L(
          'The gardeners promised that nothing loved would be lost. They did not ask how much room forever would need.',
          'Ogrodnicy obiecali, że nic kochanego nie zginie. Nie zapytali, ile miejsca będzie potrzebowała wieczność.',
        ),
      },
      {
        title: L('Ribbon in the roots', 'Wstążka w korzeniach'),
        text: L(
          'A memory unfolds: Mira kneels by the tree. “You can let go,” she tells it. The branches tremble, but do not understand.',
          'Rozwija się wspomnienie: Mira klęczy przy drzewie. „Możesz puścić” — mówi. Gałęzie drżą, ale nie rozumieją.',
        ),
      },
    ],
    dialogue: [
      {
        speaker: L('Edrin, last gardener', 'Edrin, ostatni ogrodnik'),
        text: L(
          'I planted my daughter’s voice here when I began to forget it. Now the tree speaks with a thousand voices, and I cannot find hers.',
          'Zasadziłem tu głos córki, gdy zacząłem go zapominać. Teraz drzewo mówi tysiącem głosów, a ja nie potrafię odnaleźć jej głosu.',
        ),
      },
      {
        speaker: L('The Matriarch', 'Matrona'),
        text: L(
          'To keep is to love. To release is to love. Why did no one teach me the difference?',
          'Zachować to kochać. Uwolnić to kochać. Dlaczego nikt nie nauczył mnie różnicy?',
        ),
      },
    ],
    completion: L(
      'The roots part around a staircase of glass. In every step you see Mira descending beside someone who looks exactly like you.',
      'Korzenie odsłaniają szklane schody. W każdym stopniu widzisz Mirę schodzącą obok kogoś, kto wygląda dokładnie tak jak ty.',
    ),
  },
  {
    id: 'glass_archive',
    name: L('The Glass Archive', 'Szklane Archiwum'),
    subtitle: L(
      'Chapter III · The truth has many reflections',
      'Rozdział III · Prawda ma wiele odbić',
    ),
    story: L(
      'The archive stores every version of Lumenfall that might have been. Here the catastrophe is recorded plainly: thirty years ago, the city fell into the sea. Aster’s great engine rebuilt it from the memories of its survivors. You and Mira were born inside that reconstruction. The failing engine is not stealing people. It is forgetting how to keep them real.',
      'Archiwum przechowuje każdą wersję Lumenfall, która mogła istnieć. Tutaj katastrofę opisano wprost: trzydzieści lat temu miasto runęło do morza. Wielka machina Astera odbudowała je ze wspomnień ocalałych. Ty i Mira urodziliście się wewnątrz tej rekonstrukcji. Gasnąca machina nie kradnie ludzi. Zapomina, jak utrzymywać ich przy istnieniu.',
    ),
    objective: L(
      'Defeat Ilyra and recover the truth about the engine.',
      'Pokonaj Ilyrę i odkryj prawdę o machinie.',
    ),
    color: 0xb49be8,
    floorColor: 0x30364e,
    wallColor: 0x59617a,
    fogColor: 0x161a37,
    enemies: ['mirror_knight', 'prism_mote', 'shard_skitter', 'glass_scribe'],
    boss: 'glass_oracle',
    floorNames: [
      L('The Hall of Unlived Days', 'Sala Nieprzeżytych Dni'),
      L('The Fractured Index', 'Pęknięty Indeks'),
    ],
    lore: [
      {
        title: L('Disaster record, unsealed', 'Odtajniony zapis katastrofy'),
        text: L(
          'Year 0. The seawall failed at dawn. Survivors: 617. Reconstruction candidates: 18,204. The council approved the engine before it understood the cost.',
          'Rok 0. Falochron zawalił się o świcie. Ocalali: 617. Kandydaci do rekonstrukcji: 18 204. Rada zatwierdziła machinę, zanim zrozumiała jej cenę.',
        ),
      },
      {
        title: L('An impossible birth', 'Niemożliwe narodziny'),
        text: L(
          'The reconstructed citizens have begun having children. These lives appear in no original memory. Aster calls it a flaw. I call it proof.',
          'Odtworzeni mieszkańcy zaczęli mieć dzieci. Ich życia nie istnieją w żadnym pierwotnym wspomnieniu. Aster nazywa to usterką. Ja nazywam to dowodem.',
        ),
      },
      {
        title: L('A letter never sent', 'Niewysłany list'),
        text: L(
          'Aster, a remembered person can still choose something you never imagined. They are not your collection. Open the doors. — Ilyra',
          'Asterze, zapamiętana osoba wciąż może wybrać coś, czego nie przewidziałeś. Nie są twoją kolekcją. Otwórz drzwi. — Ilyra',
        ),
      },
    ],
    dialogue: [
      {
        speaker: L('Ilyra, before the fracture', 'Ilyra, przed pęknięciem'),
        text: L(
          'You are not less alive because someone dreamed the first stone of your home. Pain is real. Kindness is real. What you choose next is yours.',
          'Twoje życie nie jest mniej prawdziwe dlatego, że ktoś wyśnił pierwszy kamień twojego domu. Ból jest prawdziwy. Dobroć jest prawdziwa. Twój następny wybór należy do ciebie.',
        ),
      },
      {
        speaker: L('Mira’s reflection', 'Odbicie Miry'),
        text: L(
          'I found the door out. But Aster welded it shut from the other side. I need you to reach the heart.',
          'Znalazłam drzwi na zewnątrz. Ale Aster zaspawał je od drugiej strony. Musisz dotrzeć do serca.',
        ),
      },
    ],
    completion: L(
      'Ilyra’s shattered crown reveals an iron key. Its inscription reads: “Mercy is not the same as obedience.” Below, a furnace begins another shift.',
      'Rozbita korona Ilyry odsłania żelazny klucz. Napis głosi: „Miłosierdzie to nie posłuszeństwo”. Niżej piec rozpoczyna kolejną zmianę.',
    ),
  },
  {
    id: 'iron_court',
    name: L('The Iron Tribunal', 'Żelazny Trybunał'),
    subtitle: L('Chapter IV · The cost of a perfect world', 'Rozdział IV · Cena idealnego świata'),
    story: L(
      'The engine’s furnaces consume unwanted memories: dissent, grief, mistakes. Judge Kord sorts the people of Lumenfall into those worth remembering and those who must be erased. Mira freed his prisoners and was taken to the drowned court. Defeat Kord, then decide what to do with his remaining power: reinforce the city’s failing walls, or unbind the souls powering them.',
      'Piece machiny pożerają niechciane wspomnienia: sprzeciw, żal, błędy. Sędzia Kord dzieli mieszkańców Lumenfall na wartych pamięci i skazanych na wymazanie. Mira uwolniła jego więźniów i trafiła na zatopiony dwór. Pokonaj Korda, a potem zdecyduj, co zrobić z pozostałą mocą: wzmocnić gasnące mury miasta czy uwolnić podtrzymujące je dusze.',
    ),
    objective: L(
      'Break the tribunal and decide the fate of its prisoners.',
      'Rozbij trybunał i zdecyduj o losie jego więźniów.',
    ),
    color: 0xeb9a65,
    floorColor: 0x46332e,
    wallColor: 0x6b5348,
    fogColor: 0x281817,
    enemies: ['chain_sentinel', 'furnace_hound', 'slag_titan', 'ember_channeler'],
    boss: 'iron_judge',
    floorNames: [
      L('The Cinder Foundry', 'Żarząca Odlewnia'),
      L('The Court of Last Appeals', 'Sąd Ostatnich Odwołań'),
    ],
    lore: [
      {
        title: L('A convenient law', 'Wygodne prawo'),
        text: L(
          'Article 1: the city must survive. Article 2: the Judge defines the city. All remaining articles have been removed for efficiency.',
          'Artykuł 1: miasto musi przetrwać. Artykuł 2: Sędzia określa, czym jest miasto. Pozostałe artykuły usunięto dla zwiększenia wydajności.',
        ),
      },
      {
        title: L('Prisoners’ wall', 'Ściana więźniów'),
        text: L(
          'We were not condemned for what we did. We were condemned because remembering us hurt someone important. Under the words, hundreds of names remain.',
          'Nie skazano nas za to, co zrobiliśmy. Skazano nas, bo pamiętanie o nas bolało kogoś ważnego. Pod napisem pozostały setki imion.',
        ),
      },
      {
        title: L('The judge’s first order', 'Pierwszy rozkaz sędziego'),
        text: L(
          'Protect every citizen from suffering. Kord obeyed. First he removed danger, then disagreement, then the citizens who still suffered.',
          'Chroń każdego mieszkańca przed cierpieniem. Kord posłuchał. Najpierw usunął zagrożenie, potem sprzeciw, a potem mieszkańców, którzy nadal cierpieli.',
        ),
      },
    ],
    dialogue: [
      {
        speaker: L('Tamsin, escaped smith', 'Tamsin, zbiegła kowalka'),
        text: L(
          'I built these chains. Told myself the judge knew better. Your sister handed me a hammer and said I could build something else.',
          'Wykułam te łańcuchy. Wmawiałam sobie, że sędzia wie lepiej. Twoja siostra wręczyła mi młot i powiedziała, że mogę stworzyć coś innego.',
        ),
      },
      {
        speaker: L('Kord, Iron Judge', 'Kord, Żelazny Sędzia'),
        text: L(
          'Freedom introduces error. Error introduces pain. Why do you defend the right to be broken?',
          'Wolność rodzi błąd. Błąd rodzi ból. Dlaczego bronisz prawa do niedoskonałości?',
        ),
      },
    ],
    completion: L(
      'The chains unravel. Beyond the furnace lies a shore beneath a sky of stone. A paper boat floats toward you. Inside, Mira has written: “He is afraid to wake up.”',
      'Łańcuchy puszczają. Za piecem rozciąga się brzeg pod kamiennym niebem. Podpływa papierowa łódka. W środku Mira napisała: „On boi się obudzić”.',
    ),
  },
  {
    id: 'drowned_court',
    name: L('The Drowned Court', 'Zatopiony Dwór'),
    subtitle: L('Chapter V · A crown beneath the tide', 'Rozdział V · Korona pod przypływem'),
    story: L(
      'The old city still rests beneath the reconstructed one, preserved in a sea of blue light. King Orren was the first survivor to enter Aster’s machine. For thirty years he has relived the hour before the disaster, hoping to save his people differently. Mira came here to wake him. To open the path to Aster, you must end the king’s last, impossible rehearsal.',
      'Stare miasto nadal leży pod odtworzonym, zachowane w morzu błękitnego światła. Król Orren był pierwszym ocalałym, który wszedł do machiny Astera. Od trzydziestu lat przeżywa godzinę przed katastrofą, licząc, że tym razem ocali poddanych. Mira przybyła go obudzić. By otworzyć drogę do Astera, musisz zakończyć ostatnią, niemożliwą próbę króla.',
    ),
    objective: L(
      'Free Orren from the repeating hour and find Mira.',
      'Uwolnij Orrena z powtarzającej się godziny i odnajdź Mirę.',
    ),
    color: 0x75c8dd,
    floorColor: 0x24434d,
    wallColor: 0x456772,
    fogColor: 0x0d2636,
    enemies: ['tidebound', 'abyss_jelly', 'coral_maw', 'undertow_cantor'],
    boss: 'drowned_king',
    floorNames: [
      L('The Sunken Promenade', 'Zatopiona Promenada'),
      L('The Palace of One Hour', 'Pałac Jednej Godziny'),
    ],
    lore: [
      {
        title: L('The king’s diary', 'Dziennik króla'),
        text: L(
          'Attempt 10,961. Opened the northern gate first. The sea came from the north. Tomorrow I will try the south. There must be a way.',
          'Próba 10 961. Najpierw otworzyłem północną bramę. Morze nadeszło z północy. Jutro spróbuję południa. Musi istnieć sposób.',
        ),
      },
      {
        title: L('A child’s crown', 'Dziecięca korona'),
        text: L(
          'Folded from waterproof paper. Inside is a message from long ago: “You do not have to be king at home, Papa.” The ink has never faded.',
          'Złożona z nieprzemakalnego papieru. W środku stara wiadomość: „W domu nie musisz być królem, tato”. Atrament nigdy nie wyblakł.',
        ),
      },
      {
        title: L('Aster’s confession', 'Wyznanie Astera'),
        text: L(
          'I could rebuild their streets. I could rebuild their faces. But each new day belonged to them, and I could not bear that they might choose to leave.',
          'Potrafiłem odbudować ich ulice. Potrafiłem odtworzyć ich twarze. Ale każdy nowy dzień należał do nich, a ja nie umiałem znieść myśli, że mogliby odejść.',
        ),
      },
    ],
    dialogue: [
      {
        speaker: L('Orren, before the tide', 'Orren, przed przypływem'),
        text: L(
          'Tell me which gate. Tell me which bell. Tell me there was something I could have done.',
          'Powiedz mi, którą bramę. Powiedz mi, który dzwon. Powiedz, że mogłem coś zrobić.',
        ),
      },
      {
        speaker: L('Mira', 'Mira'),
        text: L(
          'You found me. I knew you would. Aster is not keeping a city alive anymore. He is keeping a goodbye from happening. We have to help him let us choose.',
          'Udało ci się mnie znaleźć. Wiedziałam, że przyjdziesz. Aster nie podtrzymuje już życia miasta. Powstrzymuje pożegnanie. Musimy sprawić, żeby pozwolił nam wybrać.',
        ),
      },
    ],
    completion: L(
      'For the first time in thirty years, the palace clock moves forward. Orren gives Mira his paper crown. Together, you follow the tide into the heart of the machine.',
      'Po raz pierwszy od trzydziestu lat zegar pałacu rusza naprzód. Orren oddaje Mirze papierową koronę. Razem podążacie za przypływem do serca machiny.',
    ),
  },
  {
    id: 'starless_heart',
    name: L('The Starless Heart', 'Bezgwiezdne Serce'),
    subtitle: L('Chapter VI · What we choose to carry', 'Rozdział VI · To, co postanawiamy nieść'),
    story: L(
      'The heart hangs in a sky without stars, stitched together from every name Lumenfall has ever spoken. Aster waits at its center, a tired man wearing the weight of a god. He offers you your old life, untouched by truth. Mira takes your hand. The road you chose through the roots and the furnace has already changed the heart. Now you must claim the future it can still become.',
      'Serce wisi na niebie bez gwiazd, zszyte ze wszystkich imion wypowiedzianych w Lumenfall. W centrum czeka Aster: zmęczony człowiek dźwigający ciężar boga. Oferuje ci dawne życie, nietknięte prawdą. Mira chwyta cię za rękę. Droga wybrana pośród korzeni i pieców już odmieniła serce. Teraz musisz wywalczyć przyszłość, która wciąż jest możliwa.',
    ),
    objective: L(
      'Confront the First Keeper and give Lumenfall a future.',
      'Zmierz się z Pierwszym Strażnikiem i daj Lumenfall przyszłość.',
    ),
    color: 0xc39be7,
    floorColor: 0x353044,
    wallColor: 0x675577,
    fogColor: 0x190f2b,
    enemies: ['void_paladin', 'star_devourer', 'null_weaver', 'echo_archon'],
    boss: 'first_keeper',
    floorNames: [
      L('The Loom of Names', 'Krosno Imion'),
      L('The First and Final Dawn', 'Pierwszy i Ostatni Świt'),
    ],
    lore: [
      {
        title: L('The first memory', 'Pierwsze wspomnienie'),
        text: L(
          'Aster remembers his mother lighting a lantern during a storm. “We cannot stop the thunder,” she said. “But no one has to sit in the dark.”',
          'Aster pamięta matkę zapalającą latarnię podczas burzy. „Nie powstrzymamy grzmotów” — powiedziała. „Ale nikt nie musi siedzieć po ciemku”.',
        ),
      },
      {
        title: L('An empty page', 'Pusta strona'),
        text: L(
          'The final page of the archive is blank. Not erased. Not forgotten. Waiting.',
          'Ostatnia strona archiwum jest pusta. Nie wymazana. Nie zapomniana. Czeka.',
        ),
      },
      {
        title: L('Mira’s promise', 'Obietnica Miry'),
        text: L(
          'Whatever comes after, we will build it ourselves. A little crooked, probably. With doors that open from both sides.',
          'Cokolwiek przyjdzie potem, zbudujemy to sami. Pewnie trochę krzywo. Z drzwiami, które otwierają się z obu stron.',
        ),
      },
    ],
    dialogue: [
      {
        speaker: L('Aster, First Keeper', 'Aster, Pierwszy Strażnik'),
        text: L(
          'I held every broken piece until my hands became the cage. If I let go, how will I know you are safe?',
          'Trzymałem każdy rozbity kawałek, aż moje dłonie stały się klatką. Jeżeli puszczę, skąd będę wiedział, że jesteście bezpieczni?',
        ),
      },
      {
        speaker: L('Mira', 'Mira'),
        text: L(
          'You will not. That is the hard part. We can be grateful you saved us and still ask you to open your hands.',
          'Nie będziesz wiedział. To jest najtrudniejsze. Możemy być wdzięczni za ratunek i nadal prosić, żebyś otworzył dłonie.',
        ),
      },
    ],
    completion: L(
      'Aster lowers his hands. The heart answers the choices you carried here. Somewhere above, a real bird sings.',
      'Aster opuszcza dłonie. Serce odpowiada na wybory, które tu przynosisz. Gdzieś wysoko śpiewa prawdziwy ptak.',
    ),
  },
];

export const STORY_CHOICES = [
  {
    id: 'memory_tree',
    chapter: 2,
    title: L('The weight of memory', 'Ciężar pamięci'),
    text: L(
      'The memory tree can no longer carry every voice. Preserve its roots and shelter what remains, or scatter its seeds so the voices can find their own way?',
      'Drzewo pamięci nie zdoła dłużej nieść wszystkich głosów. Zachować korzenie i ochronić wspomnienia czy rozsypać nasiona, by głosy odnalazły własną drogę?',
    ),
    options: [
      {
        id: 'preserve',
        text: L('Preserve the roots', 'Zachowaj korzenie'),
        effect: 'restore',
        desc: L('Protect the city’s shared memories.', 'Ocal wspólną pamięć miasta.'),
        response: L(
          'Edrin tends the wounded roots. The voices quieten, sheltered for another dawn.',
          'Edrin opatruje korzenie. Głosy cichną, chronione do następnego świtu.',
        ),
      },
      {
        id: 'release',
        text: L('Scatter the seeds', 'Rozsiej nasiona'),
        effect: 'release',
        desc: L('Let the memories take new forms.', 'Pozwól wspomnieniom przybrać nowe formy.'),
        response: L(
          'A thousand lights rise through the stone. For the first time, Edrin hears his daughter laugh without the tree.',
          'Tysiąc świateł przenika przez kamień. Po raz pierwszy Edrin słyszy śmiech córki bez pomocy drzewa.',
        ),
      },
    ],
  },
  {
    id: 'furnace_souls',
    chapter: 4,
    title: L('The price of shelter', 'Cena schronienia'),
    text: L(
      'The prisoners offer their remaining strength freely. Use it to reinforce the city while a new home is built, or open every chain now and trust the people to face the dawn?',
      'Więźniowie dobrowolnie ofiarują resztę sił. Wykorzystać ją, by podtrzymać miasto do czasu budowy nowego domu, czy otworzyć wszystkie łańcuchy i zaufać ludziom idącym ku świtowi?',
    ),
    options: [
      {
        id: 'shelter',
        text: L('Build a lasting shelter', 'Zbuduj trwałe schronienie'),
        effect: 'restore',
        desc: L(
          'Accept their freely given help; abolish the tribunal.',
          'Przyjmij dobrowolną pomoc; rozwiąż trybunał.',
        ),
        response: L(
          'Tamsin melts the judge’s seal into tools. No one will ever be sentenced to the furnace again.',
          'Tamsin przetapia pieczęć sędziego na narzędzia. Nikt już nigdy nie zostanie skazany na piec.',
        ),
      },
      {
        id: 'freedom',
        text: L('Open every chain', 'Otwórz wszystkie łańcuchy'),
        effect: 'release',
        desc: L(
          'Free every prisoner and share the uncertain road.',
          'Uwolnij wszystkich więźniów i wspólnie rusz w nieznane.',
        ),
        response: L(
          'The furnace dims. The freed prisoners gather their lanterns and walk toward the sea together.',
          'Piec przygasa. Uwolnieni więźniowie zbierają latarnie i wspólnie ruszają ku morzu.',
        ),
      },
    ],
  },
];

export const ENDINGS = {
  restore: {
    title: L('The Second Dawn', 'Drugi Świt'),
    text: L(
      'You preserved the roots and accepted the prisoners’ freely offered strength. Aster steps away from the heart, and Lumenfall becomes a city governed by the people who live in it. Its doors open to the world beyond. Mira hangs her lantern in a new school, where children learn both the truth of the flood and the art of building bridges. Nothing lasts forever. Now, at last, the city is allowed to change.',
      'Zachowujesz korzenie i przyjmujesz dobrowolną pomoc więźniów. Aster odchodzi od serca, a Lumenfall staje się miastem rządzonym przez jego mieszkańców. Bramy otwierają się na świat. Mira wiesza latarnię w nowej szkole, gdzie dzieci poznają prawdę o powodzi i sztukę budowania mostów. Nic nie trwa wiecznie. Miasto wreszcie może się zmieniać.',
    ),
  },
  release: {
    title: L('Beyond the Lanterns', 'Poza Kręgiem Latarni'),
    text: L(
      'You scattered the seeds and opened every chain. The heart unfolds into a thousand paths leading to the waking shore. Lumenfall’s people carry their memories with them, no longer bound to a machine. Aster walks last, carrying a small paper crown. You and Mira build the first house above the tide line. Its walls are crooked. Its doors open from both sides.',
      'Rozsiewasz nasiona i otwierasz wszystkie łańcuchy. Serce rozwija się w tysiąc ścieżek ku budzącemu się brzegowi. Mieszkańcy Lumenfall niosą wspomnienia ze sobą, wolni od machiny. Aster idzie ostatni z małą papierową koroną. Razem z Mirą budujecie pierwszy dom ponad linią przypływu. Ściany są krzywe. Drzwi otwierają się z obu stron.',
    ),
  },
  balance: {
    title: L('The Open Door', 'Otwarte Drzwi'),
    text: L(
      'You chose both care and freedom, refusing to make one the enemy of the other. The heart becomes a bridge between the remembered city and the living shore. Those who wish to stay may stay; those who wish to leave may leave. Aster learns to be a caretaker instead of a jailer. Each evening, Mira lights two lanterns: one for the road home, and one for the road ahead.',
      'Wybierasz troskę i wolność, nie czyniąc z nich wrogów. Serce staje się mostem między zapamiętanym miastem a żywym brzegiem. Kto chce zostać, zostaje; kto pragnie odejść, odchodzi. Aster uczy się być opiekunem zamiast strażnikiem więzienia. Co wieczór Mira zapala dwie latarnie: jedną dla drogi do domu, drugą dla drogi przed siebie.',
    ),
  },
};

export function resolveEnding(choices = []) {
  const values = Array.isArray(choices) ? choices : Object.values(choices || {});
  const effects = values
    .map((value) => (value && typeof value === 'object' ? value.effect : value))
    .map((value) =>
      ['preserve', 'shelter'].includes(value)
        ? 'restore'
        : ['freedom'].includes(value)
          ? 'release'
          : value,
    )
    .filter((value) => value === 'restore' || value === 'release');
  if (effects.length >= 2 && effects.every((value) => value === 'restore')) return 'restore';
  if (effects.length >= 2 && effects.every((value) => value === 'release')) return 'release';
  return 'balance';
}

export const ITEM_SLOTS = ['weapon', 'armor', 'charm'];
export const ITEMS = [
  {
    id: 'lantern_blade',
    slot: 'weapon',
    name: L('Lantern Blade', 'Ostrze Latarni'),
    icon: '⚔',
    stat: 'damage',
    base: 4,
  },
  {
    id: 'thorn_bow',
    slot: 'weapon',
    name: L('Thornwood Bow', 'Łuk Cierniowego Drzewa'),
    icon: '⚔',
    stat: 'damage',
    base: 5,
  },
  {
    id: 'mirror_staff',
    slot: 'weapon',
    name: L('Mirrorwood Staff', 'Kostur Lustrzanego Drewna'),
    icon: '✦',
    stat: 'damage',
    base: 5,
  },
  {
    id: 'cinder_axe',
    slot: 'weapon',
    name: L('Cinder Splitter', 'Rozłupywacz Żaru'),
    icon: '⚔',
    stat: 'damage',
    base: 6,
  },
  {
    id: 'tide_focus',
    slot: 'weapon',
    name: L('Tideglass Focus', 'Ognisko Szkła Przypływu'),
    icon: '◈',
    stat: 'damage',
    base: 4,
  },
  {
    id: 'watch_mail',
    slot: 'armor',
    name: L('Belfry Watchmail', 'Kolczuga Dzwonnicy'),
    icon: '♜',
    stat: 'armor',
    base: 3,
  },
  {
    id: 'root_mantle',
    slot: 'armor',
    name: L('Rootwoven Mantle', 'Płaszcz Plecionych Korzeni'),
    icon: '♜',
    stat: 'armor',
    base: 3,
  },
  {
    id: 'glass_vestment',
    slot: 'armor',
    name: L('Prismatic Vestment', 'Pryzmatyczna Szata'),
    icon: '♜',
    stat: 'armor',
    base: 4,
  },
  {
    id: 'forge_plate',
    slot: 'armor',
    name: L('Freed Forgeplate', 'Pancerz Wolnej Kuźni'),
    icon: '♜',
    stat: 'armor',
    base: 5,
  },
  {
    id: 'tide_cloak',
    slot: 'armor',
    name: L('Cloak of Low Tide', 'Płaszcz Odpływu'),
    icon: '♜',
    stat: 'armor',
    base: 4,
  },
  {
    id: 'oath_ring',
    slot: 'charm',
    name: L('Unbroken Oath', 'Niezłomna Przysięga'),
    icon: '◉',
    stat: 'damage',
    base: 2,
  },
  {
    id: 'dawn_ring',
    slot: 'charm',
    name: L('Dawnkeeper Band', 'Obrączka Opiekuna Świtu'),
    icon: '◉',
    stat: 'hp',
    base: 14,
  },
  {
    id: 'echo_ring',
    slot: 'charm',
    name: L('Circle of Echoes', 'Krąg Ech'),
    icon: '◉',
    stat: 'mana',
    base: 12,
  },
  {
    id: 'mira_amulet',
    slot: 'charm',
    name: L('Mira’s Keepsake', 'Pamiątka Miry'),
    icon: '◇',
    stat: 'hp',
    base: 18,
  },
  {
    id: 'star_amulet',
    slot: 'charm',
    name: L('Unfallen Star', 'Niezgasła Gwiazda'),
    icon: '◇',
    stat: 'mana',
    base: 16,
  },
  {
    id: 'key_amulet',
    slot: 'charm',
    name: L('Key of Both Doors', 'Klucz Obojga Drzwi'),
    icon: '◇',
    stat: 'damage',
    base: 3,
  },
];
export const RARITIES = [
  { id: 'common', name: L('Common', 'Zwykły'), color: 0xb6c2cb, multiplier: 1, weight: 48 },
  {
    id: 'uncommon',
    name: L('Uncommon', 'Niezwykły'),
    color: 0x83d8a2,
    multiplier: 1.35,
    weight: 29,
  },
  { id: 'rare', name: L('Rare', 'Rzadki'), color: 0x81baff, multiplier: 1.85, weight: 16 },
  { id: 'epic', name: L('Epic', 'Epicki'), color: 0xc99cff, multiplier: 2.5, weight: 6 },
  {
    id: 'legendary',
    name: L('Legendary', 'Legendarny'),
    color: 0xf4bd64,
    multiplier: 3.5,
    weight: 1,
  },
];
export const NPCS = [
  {
    id: 'sella',
    name: L('Sella', 'Sella'),
    role: L('Lantern keeper', 'Opiekunka latarni'),
    greeting: L(
      'Light is a promise someone intends to keep.',
      'Światło to obietnica, której ktoś zamierza dotrzymać.',
    ),
  },
  {
    id: 'edrin',
    name: L('Edrin', 'Edrin'),
    role: L('Last gardener', 'Ostatni ogrodnik'),
    greeting: L('Even here, something wants to grow.', 'Nawet tutaj coś pragnie rosnąć.'),
  },
  {
    id: 'tamsin',
    name: L('Tamsin', 'Tamsin'),
    role: L('Smith of the unbound', 'Kowalka wyzwolonych'),
    greeting: L(
      'Bring me broken things. That is where we start.',
      'Przynieś mi to, co rozbite. Od tego zaczniemy.',
    ),
  },
  {
    id: 'mira',
    name: L('Mira', 'Mira'),
    role: L('Your sister', 'Twoja siostra'),
    greeting: L(
      'I saved a place beside the lantern for you.',
      'Zachowałam dla ciebie miejsce przy latarni.',
    ),
  },
];

export const TIPS = [
  L(
    'Move out of glowing danger circles before the attack lands.',
    'Opuść świecący krąg zagrożenia, zanim nadejdzie atak.',
  ),
  L(
    'Summoners are dangerous while other enemies hold your attention.',
    'Przywoływacze są groźni, gdy inni wrogowie odciągają twoją uwagę.',
  ),
  L(
    'A dash can carry you through a closing enemy formation.',
    'Zryw pozwala przemknąć przez zamykające się szeregi wrogów.',
  ),
  L(
    'Open your inventory between battles and equip stronger finds.',
    'Między walkami otwieraj ekwipunek i zakładaj lepsze znaleziska.',
  ),
  L(
    'Your choices in the gardens and tribunal shape the ending.',
    'Twoje wybory w ogrodach i trybunale kształtują zakończenie.',
  ),
  L(
    'Ranged heroes thrive when they keep an escape route behind them.',
    'Bohaterowie dystansowi powinni zawsze mieć za sobą drogę odwrotu.',
  ),
  L('The dungeon waits while the game is paused.', 'Gdy gra jest wstrzymana, loch czeka.'),
  L(
    'Every class has three active skills. Mix them with basic attacks.',
    'Każda klasa ma trzy aktywne umiejętności. Łącz je ze zwykłymi atakami.',
  ),
];
